name: Generate Requirements
on:
  push:
    paths:
      - "src/**"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate requirements.txt
        id: genreqs
        uses: ryan-rozario/pipreqs-action-cpy@master
        with:
          PROJECT_PATH: src
